/**:
  ros__parameters:
    map_frame: map
    arrival_check_angle_deg: 45.0  # 現在とゴールの角度の差の許容値
    arrival_check_distance: 1.0  # 現在位置とゴールの位置の距離の差の許容値
    arrival_check_duration: 0.1  # ゴール判定になる前に必要な車両の停止時間
    goal_angle_threshold_deg: 45.0
    enable_correct_goal_pose: false
